### ISSUE TITLE
Code fails when we put decimal point

### ISSUE THREAD

**Issue by codernirdesh** [prdpspkt/nepali-english-numbers-to-nepali-unicode-text#1]
I found this functionality really awesome. But, this code fails when we put decimal point as in the sample issue picture.
![image](https://user-images.githubusercontent.com/41616814/88919602-1d2d0c00-d28b-11ea-9927-3d7395e3c088.png)
I hope, you'll solve this issue ASAP!!
PEACE :)

**Comment by prdpspkt** [comment]
I have updated as needed. Please add other features if you have any idea.
